### PR TITLE
Update to CMake 3.27.4

### PR DESCRIPTION
**Pull request by mayeut**
Created by update_cmake_version.py

### CODE REVIEW

**Comment by mayeut** [comment]
@jcfr, can you yank the 3.27.4 release in PyPI please ? I placed the tag on the wrong commit...

**Comment by jcfr** [comment]
All set. The release `3.27.4` has just been yanked. 

See https://pypi.org/project/cmake/3.27.4/

**Comment by jcfr** [comment]
> we should be able to unyank later

This should indeed be possible. In the meantime `3.27.4.1` has been yanked:


image

**Comment by mayeut** [comment]
I only have limited access to internet right now but I had the chance to re-trigger the upload to PyPI and it seems it passed so the 3.27.4.1 release can probably be unyanked now.

**Comment by mayeut** [comment]
@jcfr, can you un-yank 3.27.4.1 please ?

**Comment by jcfr** [comment]
> un-yank 3.27.4.1 please

Et voila. All set :white_check_mark:

**Pull request merged**
