### PR TITLE
fix: Application bundle integrity issues on macOS 13

### LINKED ISSUE #301: Unsigned binary issues on macOS 13
I'm not able to use the pip package on macOS 13 without fighting with unsigned binaries. Guessing something has changed for signing?

### PR DESCRIPTION
**Pull request by mayeut**
This commit unbundles the macOS app to keep only what's really needed & get rid of the GUI stuff.

fix #301

### CODE REVIEW

**Comment by henryiii** [comment]
That seem reasonable. I know that the zip module in Python does not support symbolic links.  Scikit-build doesn’t handle them either. This would explain the “damaged” message.

**Comment by mayeut** [comment]
I'll try to use it a bit more but some first tests on my laptop with the wheel produced by GHA works.

**Review by henryiii — APPROVED** [review]
This fixes the issue for me, too, using the wheel locally.

**Comment by thewtex** [comment]
Thank you @mayeut !

**Pull request merged**
