### PR TITLE
chore: update to cmake 3.19.1

### PR DESCRIPTION
**Pull request by henryiii**
#114 has been updated and would be nice to include in 3.19.1's release, too. #117 looks safe to me, too.

### CODE REVIEW

**Review by jcfr — APPROVED** [review]
Thanks for the contribution :pray:

**Comment by jcfr** [comment]
The failed Travis macos amd64 job has been manually restarted.

Note: We will have to either improve the speed of the build or move away from Travis. An option would be to transition to GitHub action. I am working in that direction in the context of an other project and will integrate changes here once done.

**Comment by henryiii** [comment]
If possible, I'd highly recommend cibuildwheel. I don't know (yet) how to use it to build for ARM and PowerPC on GHA (still am using Travis for that), but it works very well and is mostly agnostic to CI systems.

**Comment by gengjiawen** [comment]
3.19.2 released.

**Comment by henryiii** [comment]
The change from a x86 to universal2 installer for macOS changes things - but I was able to update this to 3.19.1. The 3.19.2 update will be more challenging since only universal2 files are provided, and maybe this should be accompanied by a universal2 wheel too (see https://github.com/joerick/cibuildwheel/pull/484 and matching issue; I'll understand what needs to be done a bit better once that's going).

**Comment by henryiii** [comment]
@jcfr would it be a good idea to go ahead with this PR, plus maybe #114 and #117, then start working on the 3.19.2 update and possibly adding universal2 wheels? (For the reasons listed in the issue, I think we should also still provide a classic wheel for now too).

**Comment by henryiii** [comment]
cibuildwheel 1.9.0 came out yesterday, with support for Universal2 and Arm wheels cross-compiled from the normal Intel 10.15 runners. 1.8.0 had emulation support for Arm, PowerPC, and the other arch (z something?) for Linux runners.

**Comment by henryiii** [comment]
@jcfr would you like to do this PR,  #114, and #117, and then we can work on adding Universal2 support and supporting more recent releases?

**Comment by henryiii** [comment]
You got the CI working, great! Next will be to work on 3.20 and the rename. As long as the CI is working, that should be pretty easy to do, I think.

**Comment by jcfr** [comment]
> got the CI working, great! 

Credits goes to @mayeut :pray: 

>  Next will be to work on 3.20 

:ok_hand: 

In the mean time, will also address https://github.com/scikit-build/cmake-python-distributions/issues/126 and release wheels 3.19.1


> and the rename

See https://github.com/scikit-build/cmake-python-distributions/issues/132

**Comment by henryiii** [comment]
> In the mean time, will also address

Yes, already opened #133 for it. :)

Thanks @mayeut then!

**Comment by krismalfettone** [comment]
I apologize, I think I may be misunderstanding things.  I was watching both this issue / the one mentioning upgrading to 3.20 to see when they were going to get updated on pypi.  From what I could understand it looked like 3.19/3.20 should both be released and available on pypi.  However, I see that as still showing 3.18.4.post1: https://pypi.org/project/cmake/#history

Are there plans to update pypi in the future?

**Comment by henryiii** [comment]
Currently this has not been tagged and released to PyPI yet. I think we are basically ready; universal2 support, alternate Linux arch support, and single-binary support are all in. @jcfr, is there anything left before releasing? We can always do a post1 release if we have to. :) Anyway, I'm leaving releases up to @jcfr. @mayeut do any of these need to still be applied to ninja-python-distributions?

**Comment by mayeut** [comment]
> do any of these need to still be applied to ninja-python-distributions?

Yes, universal2 support, alternate Linux arch support, and single-binary support are not in the ninja-python-distributions (except for linux aarch64). You can ping me there if you want me to try and do the same thing (not planning PRs there before CMake is released because of the CMake dependency in Ninja).

**Pull request merged**
