### PR TITLE
refactor: split requirements

### PR DESCRIPTION
**Pull request by mayeut**
Pre requisite to #139 to allow installing only what's really needed at a given step.

This works well enough but I'm clearly not a fan of this as-is. Any improvement suggestions are welcome.

### CODE REVIEW

**Comment by henryiii** [comment]
> I'm clearly not a fan of this as-is.

What part are you not a fan of? This is clearly an incremental improvement, I think. There's more cleanup to be done eventually, but is there something specific related to this that you are not a fan of?

**Comment by mayeut** [comment]
>  There's more cleanup to be done eventually, but is there something specific related to this that you are not a fan of?

At least the fact that there are multiple requirements files appearing in the root folder.

As a contributor to any "simple" project, I like to try & spin-up my environment without reading the doc at first.
- Without any requirements file, I'd probably check for a doc because development dependencies are probably hidden somewhere (probably `python -m pip install -e .[dev]` or something like that)
- With one requirement file, just install this one
- With multiple, open everything to find out if there's a relationship between them.

Maybe only the `dev` one shall be kept here & the others moved to a requirement subfolder.
They are probably named well enough here for this not to be an issue though.

The fact that there are multiple ones also brings up the question, what should go in `setup.py` and what shouldn't go in there.
Why only test dependencies given you can't even run test without the full repo (i.e. you only have the wheel or the sdist) and calling `pytest` should just work. Let's just leave it out of the SDist then ?

Alternative, move everything as "extra" in `setup.py`. The issue with this one is that you can't install "only dependencies".

There's also the deploy requirement which isn't used on CircleCI. This lacks consistency.

To sum-up, I'm a bit lost with all this. @henryiii, if you say it's fine like this, I'll take your word for it. If you'd like something done differently, I'll probably learn something.

**Comment by mayeut** [comment]
back to draft: pre-requisite for this PR is #150

**Comment by henryiii** [comment]
I would generally try to solve this as much as possible via extras. "Does the package need to be installed" is a question that _usually_ has the answer "yes" - and if so, that should be an extra rather than a requirements file. Usually I have several extras, then combine them all into a `[dev]` requirement (Which, by the way, is the main reason I have any code at all in setup.py files for pure Python projects - and it's something that Poetry's fancy system doesn't actually help much with).

I think adding nox support might be useful in the long run, as well. I'll probably try to add nox and pre-commit in the future.

**Comment by henryiii** [comment]
'test' could be an extra. Deploy and repair probably need to be installed without the package, so need to break requirements files. Docs usually can be an extra too.

**Comment by henryiii** [comment]
Happy to go in as is for now, then possibly move one or more to extras later.

**Comment by jcfr** [comment]
> At least the fact that there are multiple requirements files appearing in the root folder.

Would something like this be sensible or an anti-pattern:

```
requirements/deploy.txt

```

**Comment by henryiii** [comment]
I'd generally go the other way - `tests/requirements.txt` and/or `docs/requirements.txt` if there is some reason they can't be an extra. `dev` should always be an extra, I think. Since the extension of requirements.txt is "txt", the word "requirements" is part of the file type (now who would make a filename a file type... Cough, CMakeLists.txt, cough).

Generally, requirements.txt should be locking packages for an application deployment (GitHub Dependabot can even update these locked requirements for you), but not really be a set of "extras" for a package - that's what extras is for.

But there are no hard-and-fast rules in this space.

**Comment by henryiii** [comment]
PS: I'm not against requirements/*.txt, though again I'd remove "dev", "test" and only leave deeply and repair, which only then is 2x more that a requirements folder. And there's the issue with "requirements" being part of the name vs. part of the path.

**Comment by mayeut** [comment]
Thanks for the feedback. I'll try to get this reworked a bit tomorrow morning. It's getting late here.
@jcfr, I accepted the invitation, thanks.

**Comment by mayeut** [comment]
I tried to rework this a bit using extras. It works perfectly locally but the CI doesn't play well with extras for now: it requires to build the package which requires options to be setup properly or CI should move away from ever calling `python setup.py ...`

> Happy to go in as is for now, then possibly move one or more to extras later.

Yeah, this can probably be left as-is for now and reworked later once CI moves to cibuildwheel or when current CI is reworked to move away from `python setup.py ...`

**Pull request merged**
