### PR TITLE
Update to CMake 3.21.3

### PR DESCRIPTION
**Pull request by henryiii**
Created by running `nox -s bump -- --commit`

### CODE REVIEW

**Comment by henryiii** [comment]
@mayeut probably could wait till release for #193 (and maybe #190)?

**Comment by mayeut** [comment]
> probably could wait till release for #193 (and maybe #190)?

agreed. If it does not take too long to get there, would be good to have all wheels at once.

**Comment by mayeut** [comment]
@henryiii, I will publish the tag now that #193 & #190 are merged.

**Comment by mayeut** [comment]
@henryiii, I will publish the tag now that #193 & #190 are merged.

**Pull request merged**
