### PR TITLE
ci: add ppc64le & s390x manylinux2014 builds

### LINKED ISSUE #125: PEP 599 + PEP 600 archs
PyPA has manylinux2014 and manylinux_2_24 containers on quay.io already. I think it would probably be useful to have this package distribution also publish wheels for manylinux2014_s390x / manylinux_2_24_s390x / manylinux2014_ppc64le / manylinux_2_24_ppc64le.

### PR DESCRIPTION
**Pull request by mayeut**
This adds ppc64le & s390x builds to travis-ci in order to provide manylinux2014 wheels for those platforms.

Fix #125

### CODE REVIEW

**Comment by jcfr** [comment]
@mayeut as the dependent PR have been merged, I just rebased this one and tweaked the commit message associated with the pinning of OpenSSL. 

Do not hesitate to further tweak.

**Comment by mayeut** [comment]
@jcfr,

I think we did approximately the same thing at the same time on this one. Thus I discarded your changes after rebasing on master by mistake & can't see the tweaks on OpenSSL anymore...

**Comment by jcfr** [comment]
TravisCI build associated with  ppc64le` arch failed with the following error:

image

See https://travis-ci.com/github/scikit-build/cmake-python-distributions/jobs/497242977

Suspecting an intermittent download failure, I restarted the specific travisCI job

**Comment by jcfr** [comment]
It seems to always fail:

image

See https://travis-ci.com/github/scikit-build/cmake-python-distributions/jobs/497242977

**Comment by mayeut** [comment]
@jcfr, the OpenSSL comment was a leftover of #128 attempts. I just removed it now that #128 has been merged in using new dockcross images (https://github.com/dockcross/dockcross/pull/481) not requiring to pin cryptography to an even lower version. 

I updated the arguments of the rust compiler installation too the same ones used in cryptography and that seems to do the trick for the ppc64le download.

Finally, there were some resource issues on ppc64le that were worked around limiting the number of parallel builds to 4.

**Review by henryiii — APPROVED** [review]
@jcfr Looks good to me. Worth including before 3.19.1, perhaps?

**Comment by henryiii** [comment]
To be useful, this probably needs to be applied to https://github.com/scikit-build/ninja-python-distributions too?

**Pull request merged**
