### PR TITLE
Update to CMake 3.16.3

### PR DESCRIPTION
**Pull request by henryiii**
Note that 3.16.0 has not been released to PyPI yet.

### CODE REVIEW

**Comment by jcfr** [comment]
Thanks for the PR :pray: 

Look like something is wrong with `tests/test_distribution.py::test_wheel`

**Comment by jcfr** [comment]
I also think we should remove support for python 2.7

**Comment by henryiii** [comment]
I would actually uncharacteristically recommend keeping python 2.7 support for a bit longer; this is a good way to grab cmake using the system pip and python on CentOS 7 and similar systems, and in CI. A user may not be using Python at all and therefore getting Python 3 just to install CMake is overkill.

**Comment by jcfr** [comment]
> uncharacteristically recommend keeping python 2.7 support for a bit longer

:+1: 

> Look like something is wrong with tests/test_distribution.py::test_wheel

Is it something you could look into ? :pray: 

Currently at a conference, I have a limited bandwidth.

**Comment by henryiii** [comment]
I can try, but am traveling too. Will be back Sunday.

**Comment by henryiii** [comment]
Looks like this fixed itself, actually.

**Comment by Croydon** [comment]
There is still no 3.16.x release on pypi? 🤔 

https://pypi.org/project/cmake/#history

**Comment by jcfr** [comment]
Thanks for the ping 🙏 

I will push the corresponding tag, and wheels will be uploaded to PyPI.

See https://cmake-python-distributions.readthedocs.io/en/latest/make_a_release.html#pypi-step-by-step

**Comment by jcfr** [comment]
> I will push the corresponding tag, and wheels will be uploaded to PyPI.

Will do this asap ... currently in the ✈️

**Comment by thewtex** [comment]
:tada: :taco: https://pypi.org/project/cmake/3.16.3/

**Pull request merged**
