### PR TITLE
feat: cross-compile to Windows ARM

### PR DESCRIPTION
**Pull request by henryiii**

### CODE REVIEW

**Comment by jcfr** [comment]
Thanks for working on this :pray: :rocket: 

If relevant, let's also make sure to update [scripts/update_cmake_version.py](https://github.com/scikit-build/cmake-python-distributions/blob/master/scripts/update_cmake_version.py)

**Comment by henryiii** [comment]
Oops, yes, you are right, I forgot about that. My next step is to bump to the next patch version, so I’d have hit it there. Much better preemptive!

**Comment by henryiii** [comment]
Update seems to work locally.

**Comment by henryiii** [comment]
Ah, also todo: probably should check this. Since we are just downloading the ARM binary, I'd expect it to be fine, but let's make sure. It does bother me that no tests failed.

**Pull request merged**
