### PR TITLE
Enable win-arm64 by x86-emulated version

### PR DESCRIPTION
**Pull request by gaborkertesz-linaro**
Currently there is no win-arm64 CMake release yet, but x86 emulated version is working properly.
As soon as CMake is released for win-arm64, that binary should be targeted.

### CODE REVIEW

**Comment by gaborkertesz-linaro** [comment]
@henryiii Could you take a look on that?

**Comment by henryiii** [comment]
Seems reasonable.

**Comment by gaborkertesz-linaro** [comment]
@henryiii thanks for the quick cooperation! Could you estimate when it will be released at pypi?

**Comment by henryiii** [comment]
3.23 is about out, probably then? We match numbering schemes, so doing patch releases on patch releases is not ideal if it's easy to avoid.

**Comment by henryiii** [comment]
3.23 is stuck due to loss of manylinux1 support, but 3.22.4 will have this (tomorrow, probably)

**Pull request merged**
